#!/usr/bin/env bash
#
# |Arquivos de Configuração
#
#  Email:      paulogcsouza86@hotmail.com
#  Autor:      Paulo Souza                 Manutenção: Paulo Souza
#
# -------------------------------------------------------------------------#
#  Histórico:
#   v1.0 30/5/2020 (Começou a funcionar)
#   v1.2 1/6/2020  (melhorias no funcionamento e novas funções add)
#  Testado em:
#   bash 4.4.20(1)

VERMELHO="\033[31;1m"
CIANO="\033[36;1m"
CINZA="\033[37;1m"
AMARELO="\033[33;1m"
# ---------------------------------TESTE---------------------------------- #
echo "Você gostaria de informações sobre o sistema? [s/n] "
read RESPOSTA0
test "$RESPOSTA0" != "s" && exit

# --------------------------------EXECUÇÂO-------------------------------- #
echo -e "$CIANO Data e horário local:"
date                                      #data local
echo
echo -e "$VERMELHO Uso do disco:"
df -h                                    #Uso da memória
echo
echo -e "$CINZA Usuários conectados:"
w                                        #Usuários logados
echo

# ---------------------------------TESTE---------------------------------- #

echo -e "Gostaria de Informações complementares Sobre o Hardware [s/n]"
read RESPOSTA1
test "$RESPOSTA1" != "s" && echo -e "$AMARELO Tenha um bom dia !!!" && exit
lscpu | lscpu | sed -n '1,24p' # lista apenas as 24 primeiras linhs (Que são as relevantes para essa função )
