#!/usr/bin/env bash
#
# Buscar dados do hardware
#
#  Email:      paulogcsouza86@hotmail.com
#  Autor:      Paulo Souza                 Manutenção: Paulo Souza
#
# -------------------------------------------------------------------------#
#  Histórico:
#   v1.0 30/5/2020 (Começou a funcionar)
#  Testado em:
#   bash 4.4.20(1)

VERMELHO="\033[31;1m"
CIANO="\033[36;1m"
CINZA="\033[37;1m"
# ------------------------------- INTERAÇÂO------------------------------- #

echo "Vou buscar os dados do sistema. Posso continuar? [s/n] "
read RESPOSTA

# ---------------------------------TESTE---------------------------------- #

test "$RESPOSTA" != "s" && exit

# --------------------------------EXECUÇÂO-------------------------------- #
echo -e "$CIANO Data e horário local:"
date
echo
echo -e "$VERMELHO Uso do disco:"
df -h
echo
echo -e "$CINZA Usuários conectados:"
w
